### PR TITLE
link corrections to reduce redirects

### PR DESCRIPTION
**Pull request by akomakom**
Trying to reduce noise in [link checker results](https://validator.w3.org/checklink?uri=http%3A%2F%2Fwww.terracotta.org%2F&hide_type=all&recursive=on&depth=5&check=Check) by minimizing redirects

~@jhouserizer Any suggestions for fixing these broken links?~
* ~https://www.terracotta.org/files/artifacts/terracotta-store-client-10.3.0.1.87-javadoc.zip~
* ~https://www.jetbrains.com:443/idea/features/code_analysis.html~

### CODE REVIEW

**Comment by terracotta-org** [comment]
[A Live Preview](https://5ff5ca2b4534ce105653f95c--terracotta-org.netlify.app) of this Pull Request at commit 2aff6ea1f23a33ebd929704a4132a488b65ee7d9 is now available

**Comment by terracotta-org** [comment]
[A Live Preview](https://5ff5cf0d4534ce1e8053f6a2--terracotta-org.netlify.app) of this Pull Request at commit 9d7460043f042e1a46ec13bf5d987a47402e9f06 is now available

**Comment by terracotta-org** [comment]
[A Live Preview](https://5ff5d10dbd77651d1d45cfc0--terracotta-org.netlify.app) of this Pull Request at commit f26567c239c9fdfdd1df71b4d1d2e69a455198f6 is now available

**Comment by terracotta-org** [comment]
[A Live Preview](https://5ff5d247bd77651dec45cfd8--terracotta-org.netlify.app) of this Pull Request at commit f70bbb52a7a36b40e9e1cf5f01812fca3711722a is now available

**Comment by terracotta-org** [comment]
[A Live Preview](https://5ff5d510cc383414f8f5b685--terracotta-org.netlify.app) of this Pull Request at commit 1609cb89c7cceb8d2b0fe73c36dc7c715fb1b2a4 is now available

**Comment by terracotta-org** [comment]
[A Live Preview](https://5ff5d5b062ce80f43ebe7901--terracotta-org.netlify.app) of this Pull Request at commit ccc4aef02599b3682e3d53cfc4aa18ed019687f2 is now available

**Comment by terracotta-org** [comment]
[A Live Preview](https://5ff5d924efedb10b56ec3a6a--terracotta-org.netlify.app) of this Pull Request at commit bf0bfe8bd988d6835ba48d4d47c8f8c72f157c3d is now available

**Comment by terracotta-org** [comment]
[A Live Preview](https://5ff5f3001b2c7b01591ba007--terracotta-org.netlify.app) of this Pull Request at commit ef96706a555bd1a7d10930d84fc1f9b97b8ceaa5 is now available

**Comment by terracotta-org** [comment]
[A Live Preview](https://5ff5f572ea81f0084985c38c--terracotta-org.netlify.app) of this Pull Request at commit 470072924ed4399b1a6970ced80d690d9a6d1b64 is now available

**Comment by akomakom** [comment]
@jhouserizer This should be good to go.  
Hi @fossf

**Pull request merged**
